# Imagen base
FROM node:18

# Crea el directorio de trabajo
WORKDIR /app

# Copia los archivos necesarios
COPY package*.json ./
RUN npm install

# Copia el resto del código fuente
COPY . .

# Compila TypeScript
RUN npm run build

# Expone el puerto del backend
EXPOSE 3000

# Comando de inicio
CMD ["node", "dist/server.js"]
